### ISSUE TITLE
Add filtering when fetching per user 

### ISSUE THREAD

**Issue by tyler46** [peterbe/github-pr-triage#23]
Hi :) 

When selecting to view the pr via username, it fetches all user's events. I think we want only on the events that have type either _PullRequestEvent_ or _PullRequestReviewCommentEvent_ . I have checked [Github docs](https://developer.github.com/v3/activity/events/types/) but I haven't found a way to filter them when making the HTTP request. So a filtering can be done on client side after all events have been fetched. 
Does it make any sense this to you?

thanks

**Comment by peterbe** [comment]
According to [this post](http://stackoverflow.com/a/18734612/205832) your only option is to do client-side filtering.

**Comment by peterbe** [comment]
I think we need `IssueCommentEvent` too. [This, for example](https://github.com/mozilla/airmozilla/pull/220#issuecomment-77435174), is a IssueCommentEvent. It's a comment on a pull request that is not tied to a particular line of code.

**Comment by tyler46** [comment]
Yeap, I was afraid so. What do you think of adding that filtering to get only the pr related events?

**Comment by peterbe** [comment]
I think it's crucial that `mozilla/airmozilla` gets included because I've post a comment there on a pull request.

**Comment by peterbe** [comment]
I made a patch that filters on 
```javascript
var filter_event_types = [
            'PullRequestReviewCommentEvent',
            'PullRequestEvent',
            'IssueCommentEvent',
        ];
```

**Before**
![screenshot 2015-03-06 09 30 29](https://cloud.githubusercontent.com/assets/26739/6530181/888036a6-c3e3-11e4-8a5c-5a1a36d77341.png)
**After**
![screenshot 2015-03-06 09 31 26](https://cloud.githubusercontent.com/assets/26739/6530190/94880460-c3e3-11e4-945b-14e5b71a4c63.png)

Does that seem right?

**Comment by tyler46** [comment]
for me yes, because I haven't made any pr recently on any of my (forked or not) repos. I think it's more suitable to test it with your activity, since you will get a proper idea of what filter removes. Sounds reasonable?

**Comment by tyler46** [comment]
In any case, this is up to what information do you want to propagate.

**Comment by peterbe** [comment]
Ok. I have a patch ready. It's making a finer distinction on those `IssueCommentEvent` payloads. 
Hold tight.

**Comment by tyler46** [comment]
:+1  :)
