### ISSUE TITLE
Update the Heroku app name from enigmatic-beyond-2991

### ISSUE THREAD

**Issue by edmorley** [peterbe/github-pr-triage#28]
The Heroku app is currently named `enigmatic-beyond-2991` (a Heroku auto-generated name) which confuses me every time I see it in the org apps list.

Would you mind renaming it to something clearer?
https://devcenter.heroku.com/articles/renaming-apps

I believe this will mean updating the CNAME on the http://prs.mozilla.io/ domain too.

**Comment by peterbe** [comment]
@lonnen If @edmorley updates the sub-domain to something sensible, can you update the DNS CNAME to whatever he changes it to?

**Comment by lonnen** [comment]
I cannot log in to do this now, but sure

**Comment by lonnen** [comment]
updated in heroku and s3. new url is [pr-triage.herokuapp.com](http://pr-triage.herokuapp.com). You may need to fix your remotes. https://devcenter.heroku.com/articles/renaming-apps#updating-git-remotes

**Comment by edmorley** [comment]
Many thanks!

**Comment by peterbe** [comment]
Ugh?
```
▶ heroku apps:rename pr-triage --app enigmatic-beyond-2991
Renaming enigmatic-beyond-2991 to pr-triage... !
 ▸    Couldn't find that app.
```

**Comment by peterbe** [comment]
```
git remote set-url heroku https://git.heroku.com/pr-triage.git
```
probably works too.
